services:
  frontend:
    build: ./frontend
    container_name: projecty_frontend_container
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
    - backend

  backend:
    build: ./backend
    container_name: projecty_backend_container
    ports:
      - "${BACKEND_PORT}:80"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - projecty_datenbank

  projecty_datenbank:
    image: mysql:8.0
    container_name: projecty_mysql
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: projecty_phpmyadmin_container
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - projecty_datenbank

volumes:
  db_data: